### ISSUE TITLE
CanvasRenderer using incorrect asset from spritesheet

### ISSUE THREAD

**Issue by jake** [pixijs/tilemap#122]
I'm attempting to get pixi.js legacy canvas support working, but having an issue with this library. It seems to be ignoring the x,y position within the spritesheet and just displaying from 0,0. 

Here is a slimmed down demo exhibiting the issue: https://codepen.io/jacobbijani/pen/XWMBdXr

Here is the code from that link just in case:

```javascript
import * as PIXI from "https://cdn.skypack.dev/pixi.js-legacy";
import { CanvasTileRenderer, CompositeTilemap } from "https://cdn.skypack.dev/@pixi/tilemap";

if (!PIXI.utils.isWebGLSupported()) {
  console.log('no webgl, registering canvas plugin')
  PIXI.CanvasRenderer.registerPlugin('tilemap', CanvasTileRenderer);
}

// NOTE: `json` variable is defined in HTML tab

var app = new PIXI.Application({
    width: window.innerWidth,
    height: window.innerHeight,
    backgroundColor: 0x2c3e50
});
document.body.appendChild(app.view);

new PIXI.Spritesheet(PIXI.Texture.from('https://thinko-artifacts.s3.amazonaws.com/codepen/tiles-half.png'), json).parse((sheet) => {
  console.log('sheet loaded', sheet);
  
  const tilemap = new CompositeTilemap();
  app.stage.addChild(tilemap);

  tilemap.clear();
  tilemap.tile('vehicle-engine', 0, 0);
  tilemap.tile('vehicle-tractor', 0, 32);
});
```

In Chrome I see this, which is what is expected:

<img width="53" alt="Screen Shot 2021-06-08 at 11 26 22 AM" src="https://user-images.githubusercontent.com/285917/121214114-d1ed6d80-c84c-11eb-8f87-03d1b6e25508.png">

In Firefox, where I have webgl disabled, I see this:

<img width="119" alt="Screen Shot 2021-06-08 at 11 26 15 AM" src="https://user-images.githubusercontent.com/285917/121214224-e3367a00-c84c-11eb-96e0-d41e76f5c25d.png">

The red dot is what is at 0,0 of my spritesheet. 

Am I doing something wrong, or is this a bug?

**Comment by ivanpopelyshev** [comment]
OK, found bug, if you want to try fast fix, apply this to your @pixi/tilemap file in node_modules or where is it https://github.com/pixijs/tilemap/commit/7938df83d6ff7da591bb179d98c2d5cd67e8c602

also, you wont need to register canvas renderer after this

**Comment by jake** [comment]
thanks for the prompt response! that does seem to work, but it seems i still need the registerPlugin call for it to work. 

if I remove the `PIXI.CanvasRenderer.registerPlugin('tilemap', CanvasTileRenderer);` then I get a separate error I got prior as well:

<img width="789" alt="Screen Shot 2021-06-08 at 12 28 43 PM" src="https://user-images.githubusercontent.com/285917/121223029-1846ca80-c855-11eb-897f-1e4920238a2c.png">

when I inspect the breakpoint there, it seems my `tileAnim` is actually null. presumably since both `this.tileAnim` is null and `renderer.plugins.tilemap.tileAnim` is undefined. 

perhaps registerPlugin is still just required? or maybe the `tileAnim` fallback a few lines up is missing something?

**Comment by ivanpopelyshev** [comment]
oh right because `Tilemap` doesnt have tileAnim by default... :)

**Comment by jake** [comment]
great! btw, it took me a bit of sleuthing to realize I needed to register that. seems like its only documented in the actual `tilemap/src/CanvasTileRenderer.ts ` source. a section in the readme on "enabling canvas support" might be worthwhile. I'd write it but honestly I'm not sure I have a full enough grasp on how it works just yet :)

**Comment by ivanpopelyshev** [comment]
Anyway, its fixed in latest release, but still needs to register plugin

**Comment by jake** [comment]
sounds good. when will it be published to npm?

**Comment by ivanpopelyshev** [comment]
it wasnt? Oh, I just have to call @ShukantPal again. I cant build new version for some reason :(

**Comment by jake** [comment]
correct, on github and npm the latest version is still 3.2.0

**Comment by jake** [comment]
@ShukantPal sorry to be annoying, but any update on publishing a new build to npm? hoping to get this integrated in my game upstream. 

thanks!

**Comment by ShukantPal** [comment]
I'll look into this today. Was gone on vacation.

**Comment by ShukantPal** [comment]
https://github.com/pixijs/tilemap/releases/tag/v3.2.1
