### ISSUE TITLE
Update to newer PIXI version

### ISSUE THREAD

**Issue by Ayfri** [pixijs/tilemap#136]
Hello, it would be great to have this project updated to latest PIXI 6.x version, there are surely some optimizations and refactoring possible that could increase performances.

**Comment by ivanpopelyshev** [comment]
According to https://github.com/pixijs/tilemap/blob/e7d26dde5b47a9ea941c50e62ad151acfc7ca57b/package.json#L55-L60 it should work with any v6, and i dont htink there were any big changes that break compatibility
