### ISSUE TITLE
Not compatible with Pixi 7

### ISSUE THREAD

**Issue by spassvogel** [pixijs/tilemap#145]
when trying to install @pixi/tilemap with pixijs 7

```
npm ERR! Could not resolve dependency:
npm ERR! @pixi/tilemap@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @pixi/core@6.5.8
npm ERR! node_modules/@pixi/core
npm ERR!   peer @pixi/core@"^6.0.4" from @pixi/tilemap@3.2.2
npm ERR!   node_modules/@pixi/tilemap
npm ERR!     @pixi/tilemap@"*" from the root project
```

**Comment by ivanpopelyshev** [comment]
Yes, still working on moving all my plugins to v7.

**Comment by spassvogel** [comment]
Great! Let me know if there's something I can do to help

**Comment by steel97** [comment]
> when trying to install @pixi/tilemap with pixijs 7
> 
> ```
> npm ERR! Could not resolve dependency:
> npm ERR! @pixi/tilemap@"*" from the root project
> npm ERR! 
> npm ERR! Conflicting peer dependency: @pixi/core@6.5.8
> npm ERR! node_modules/@pixi/core
> npm ERR!   peer @pixi/core@"^6.0.4" from @pixi/tilemap@3.2.2
> npm ERR!   node_modules/@pixi/tilemap
> npm ERR!     @pixi/tilemap@"*" from the root project
> ```

It's quite easy to get this plugin work with pixi v7. Just update dependencies and change `Renderer.registerPlugin` to `extensions.add` in `index.ts` and `CanvasTileRenderer.ts`, also change `AbstractRenderer` to `IRenderer`.
Here is my fork: https://github.com/steel97/pixi-tilemap/tree/v7_dev
Changes that I made:
- updated all packages
- changed code to be compatible with pixi v7
- added prepare script to be able to install plugin directly from github
- updated basic example

Also made vue3 + pixi-tilemap example: 
Code: https://github.com/steel97/vue3-pixi-tilemap
Github pages example: https://steel97.github.io/vue3-pixi-tilemap/

**Comment by ivanpopelyshev** [comment]
Yes, i forgot about this plugin. I have private v7 workin vesion with same thing.Thank you, your branch will defeinitely help me because its tested!

**Comment by spassvogel** [comment]
Looking forward :)

**Comment by yliaho** [comment]
So from what I can gather, v7 dropped support for canvas, and plugins now have a completely different interface.

Are there any other breaking changes that we know of? @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
Yo, @steel97 can i just merge yours? People say it works good.

**Comment by steel97** [comment]
@ivanpopelyshev 
Sure. However, I had to remove lastest pixi github workflow as it rely on outdated workflow:
https://github.com/pixijs/tilemap/blob/daf420ee1aafcc59d4dd2f1da3366dbca54ecc01/.github/workflows/pixijs.yml#L43
Also I reverted rollup and it's plugins from latest version to currently used, mostly because of this outdated plugin https://github.com/pixijs/tilemap/blob/daf420ee1aafcc59d4dd2f1da3366dbca54ecc01/package.json#L64
I made pull request, should work fine with pixi v7.
In future it would be cool to remove peerDependencies, switch build tools to vite and remove all outdated plugins, for reference here is awesome work that @cuire made for pixi-viewport (https://github.com/davidfig/pixi-viewport/pull/428)

**Comment by jamespohalloran** [comment]
Can this ticket be closed? I'm getting some mixed messages on if Pixi 7 is supported, so looking for some clarification:

Readme says:
> It's designed to work with PixiJS 7. 

The Pixi Migration doc on the other hand says its not compatible with v7:
https://pixijs.com/guides/migrations/v7?_highlight=tilemap#%EF%B8%8F-plugin-supported

Thanks!

**Comment by steel97** [comment]
> Can this ticket be closed? I'm getting some mixed messages on if Pixi 7 is supported, so looking for some clarification:
> 
> Readme says:
> 
> > It's designed to work with PixiJS 7.
> 
> The Pixi Migration doc on the other hand says its not compatible with v7: https://pixijs.com/guides/migrations/v7?_highlight=tilemap#%EF%B8%8F-plugin-supported
> 
> Thanks!

PIXI v7 supported since this PR: https://github.com/pixijs/tilemap/pull/148
