### ISSUE TITLE
Cannot read property 'registerPlugin' of undefined (using webpack)

### ISSUE THREAD

**Issue by Oza94** [pixijs/tilemap#15]
Hello again,

So I'm trying to import `pixi-tilemap` in a project built using webpack. The following fails : 

```js
import 'pixi.js'; 
// `PIXI` now available in global scope
import 'pixi-tilemap';
```

When I inspect, the error seems to be thrown by [this line](https://github.com/pixijs/pixi-tilemap/blob/08501ffe5f198131eb168d461090a91d404e6dbf/src/CanvasTileRenderer.ts#L13). Any idea why this fails ? I'm already using this method for other pixi plugins (like `pixi-particles`).

Here are my libraries versions from `yarn.lock` : 

```text
pixi-tilemap@^1.2.3:
  version "1.2.3"
  resolved "https://registry.yarnpkg.com/pixi-tilemap/-/pixi-tilemap-1.2.3.tgz#63306cb5c1c847279a249f3e1f064140f26e0470"
  dependencies:
    glslify "^5.0.2"
    typescript "^2.2.2"

pixi.js@^4.5.2:
  version "4.5.2"
  resolved "https://registry.yarnpkg.com/pixi.js/-/pixi.js-4.5.2.tgz#22b63b0c42185ac204e01086aff7ebeb60de0e0c"
  dependencies:
    bit-twiddle "^1.0.2"
    earcut "^2.0.7"
    eventemitter3 "^2.0.0"
    ismobilejs "^0.4.0"
    object-assign "^4.0.1"
    pixi-gl-core "^1.0.3"
    remove-array-items "^1.0.0"
    resource-loader "^2.0.6"

webpack@^2.6.1:
  version "2.6.1"
  resolved "https://registry.yarnpkg.com/webpack/-/webpack-2.6.1.tgz#2e0457f0abb1ac5df3ab106c69c672f236785f07"
  dependencies:
    acorn "^5.0.0"
    acorn-dynamic-import "^2.0.0"
    ajv "^4.7.0"
    ajv-keywords "^1.1.1"
    async "^2.1.2"
    enhanced-resolve "^3.0.0"
    interpret "^1.0.0"
    json-loader "^0.5.4"
    json5 "^0.5.1"
    loader-runner "^2.3.0"
    loader-utils "^0.2.16"
    memory-fs "~0.4.1"
    mkdirp "~0.5.0"
    node-libs-browser "^2.0.0"
    source-map "^0.5.3"
    supports-color "^3.1.0"
    tapable "~0.2.5"
    uglify-js "^2.8.27"
    watchpack "^1.3.1"
    webpack-sources "^0.2.3"
    yargs "^6.0.0"
```

**Comment by ivanpopelyshev** [comment]
I dont use webpack, but we have something in pixi-spine plugin: https://github.com/pixijs/pixi-spine/blob/master/sandbox/webpack.config.js

Looks like you need to specify pixi and other things in config.

webpack.config.js

```
module.exports = {
  entry: {
    'your_app': ['./lib/pixi-spine.js', ...]
  },
  externals: {
    'pixi.js': 'PIXI'
  },
}
```

**Comment by Oza94** [comment]
I tried with `externals` and `ProvidePlugin` without success. It seems that `PIXI` is undefined when webpacks loads the `bin/pixi-tilemap.js`. 

> I really cant help more. I personally think that PIXI and all libs should not be processed through webpack.

I have to disagree on that ^^' Since PIXI uses es6 with module imports it allows tree shaking and other nice features with webpack ! A bit tedious to setup but once it works it rocks ! Also I really don't want to manage third-party libs as additional entries in my webpack config. 

I'll dig more on webpack config, probably a simple tweak that I miss here can solve the issue. Otherwise I'll try to require the source files directly with a TypeScript loader dedicated to `pixi-tilemap`. If I manage to process it with webpack I'll report here ;) 

Thanks for the advice anyway !

**Comment by ivanpopelyshev** [comment]
Yeah, you might have to edit resulting js file to make it compatible with webpack. It wasnt easy to make pixi-spine compatible with everything, and I still dont understand how it works.

**Comment by roryclaasen** [comment]
@Oza94 did you manage to get this working?
I am currently having this same issue and don't see any alternative to pixi-tilemap

**Comment by ivanpopelyshev** [comment]
i  didnt make it compatible with webpack, sorry. you have to wait more or do it yourself.

**Comment by agemor** [comment]
@roryclaasen Add  `"@types/pixi.js": "^4.7.1"` to dependencies in `pixi-tilemap` package.json. Build it agian, and it should be working.

The problem was: webpack compiler is creating new `PIXI` variable because `pixi.js` is missing in dependency list.

**Comment by ivanpopelyshev** [comment]
Try new version (1.2.4) from npm or from `dist` folder of this repo.

**Comment by roryclaasen** [comment]
@ivanpopelyshev sorry for getting back late. This works a charm now thank you!
