### ISSUE TITLE
`Cannot find module '@pixi/tilemap' or its corresponding type declarations`

### ISSUE THREAD

**Issue by jerrygreen** [pixijs/tilemap#159]
Are TypeScript types gonna be added?

**Comment by ivanpopelyshev** [comment]
For v8, latest, right?

**Comment by ivanpopelyshev** [comment]
I dont have time to manage small things like types, honestly, all those scripts are not my forte. Thus, i'm waitin for help with
1. types
2. examples.
if you manage to fix types - I'll accept PR )

**Comment by jerrygreen** [comment]
Latest version downloaded from npm, yes.

And v8… Aren’t they all for v8?

It looks like the project is done with TypeScript isn’t it? I wonder why the types aren’t found. I didn’t pay attention when I saw this error, thought it’s non-typescript library, so created the issue right-away. I will re-check soon, maybe I can help with that 👍

**Comment by jerrygreen** [comment]
Just gave it a try again, now suddenly I don't have this problem anymore. Guess my node_modules were messed up, no issue!
