### ISSUE TITLE
[SUGGESTION] Use `dist`  instead of `bin` 

### ISSUE THREAD

**Issue by finscn** [pixijs/tilemap#18]
Use `dist`  instead of `bin`,  as same as other pixi projects.

And add `dist` to .gitignore.

And I hope could build  pixi-tilemap.min.js version.

**Comment by finscn** [comment]
I don't know how to build pixi-tilemap.min.js .

**Comment by ivanpopelyshev** [comment]
Dont build it, let people use big version. I hate mins.

**Comment by ivanpopelyshev** [comment]
Btw, new plugin is coming! And tilemap will depend on it: https://github.com/gameofbombs/pixi-super-atlas
