### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by SET001** [pixijs/tilemap#56]
are there docs for this library?

**Comment by ivanpopelyshev** [comment]
https://github.com/Alan01252/pixi-tilemap-tutorial

Also, the thing I tell everyone, the most effective way to use pixi-tilemap:

Make a "window" around a camera, fill tilemap with tiles that fit that window, reposition the window and refill tiles every time camera hits edge of window. Unfortunately, no one made tutorial like that. I guess its too hard to make several "if"s and two "for" cycles ;)

**Comment by SET001** [comment]
Yeah, I saw that tutorial but I mean a documentation on each exported class, properties, methods (API).For now I have to read sources (thanx to gods it build on TypeScript which make it more self-descriptive)

**Comment by ivanpopelyshev** [comment]
It'll be easier for pixi-v5, because most of this stuff already present in it.

**Comment by SukantPal** [comment]
The docs have been added here:- https://api.pixijs.io/@pixi/tilemap.html btw.
