### ISSUE TITLE
There is no `@types/pixi-tilemap`.

### ISSUE THREAD

**Issue by finscn** [pixijs/tilemap#62]
I wan't create a extension project about pixi-tilemap with ts , but there is no `@types/pixi-tilemap`.

could you add it ,please ?  @ivanpopelyshev 

(BTW, the version on npmjs is out of date)

Thanks

**Comment by finscn** [comment]
I know I could use `.d.ts` file directly , But it's not elegant.

**Comment by ivanpopelyshev** [comment]
pixi-tilemap already contains d.ts and its referenced in `package.json` file. `@types/` exist only for projects which dont have types in package.json.
