### ISSUE TITLE
What are the bitmaps for

### ISSUE THREAD

**Issue by spassvogel** [pixijs/tilemap#89]
PIXI.tilemap.CompositeRectTileLayer has a second constructor parameter named ` bitmaps?: PIXI.Texture[] `. However I have found that it is completely optional, if I dont provide anything there and pass a texture to addFrame it works. I don't really understand what this bitmaps is used for..

**Comment by ivanpopelyshev** [comment]
usually its not important. It was made before we had `addFrame` that has auto-search of baseTexture in array and adds stuff automagically.

Only in really hecked-up cases you have to fill it with textures of different baseTexture's to specify the exact order in texture array.

**Comment by spassvogel** [comment]
I see. So does that mean that this info in the readme.md is also not relevant anymore?

<img width="877" alt="image" src="https://user-images.githubusercontent.com/985892/87244333-c2975180-c43c-11ea-8123-8a6ca881211c.png">

**Comment by ivanpopelyshev** [comment]
Oh its relevant! Its so relevant, people stumble across it very often.

There are devices that dont have 16 texture locations.

Now, imagine, someone wants it all automatic, default v5 mode - 16 textures. He encounters devices that doesnt have it.

Imagine that I make by default maxTextures 4 with packing (4 textures to 1) - someone will try big textures on it and it wont work

**Comment by SukantPal** [comment]
The bitmaps will predefine the tileset and initialize enough tilemaps. Doing `addFrame` without passing `bitmaps` will lazily build the tileset.
